# Generated by cucumber-sinatra. (2014-05-13 18:02:56 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', './lib/prs.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = PRS

class PRSWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  PRSWorld.new
end
